### ISSUE TITLE
Syntax error.

### ISSUE THREAD

**Issue by divinerapier** [bytedance/go-querystring-parser#1]
I want to parse a search like 
```
"a: 1 or ( b : 2 and c : 3) "
```
but got an error
```
syntax error: unexpected tSTRING, expecting tRIGHTBRACKET
```

**Comment by samuelncui** [comment]
This problem is fixed, you can try the newest version.
https://github.com/bytedance/go-querystring-parser/commit/dcfffcaee797667f4572f6f881dab7569b1c5856
